<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-03-08 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.0.2 on 2024-03-06 19:09

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> origin/master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> origin/master
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_style', models.CharField(choices=[('Adventure Seeker', 'Adventure Seeker'), ('Cultural Explorer', 'Cultural Explorer'), ('Luxury Traveler', 'Luxury Traveler'), ('Budget Traveler', 'Budget Traveler'), ('Family Traveler', 'Family Traveler'), ('Solo Traveler', 'Solo Traveler'), ('Eco-conscious Traveler', 'Eco-conscious Traveler')], max_length=100)),
                ('activity_preferences', models.CharField(blank=True, choices=[('Outdoor Activities', 'Outdoor Activities'), ('Sightseeing/Cultural Activities', 'Sightseeing/Cultural Activities'), ('Food and Wine Experiences', 'Food and Wine Experiences'), ('Relaxation/Wellness Activities', 'Relaxation/Wellness Activities'), ('Adventure Sports', 'Adventure Sports'), ('Shopping', 'Shopping')], max_length=100)),
                ('destination_preferences', models.CharField(blank=True, choices=[('Beach Destinations', 'Beach Destinations'), ('Mountain Destinations', 'Mountain Destinations'), ('Urban Destinations', 'Urban Destinations'), ('Historical/Cultural Destinations', 'Historical/Cultural Destinations'), ('Nature/Wildlife Destinations', 'Nature/Wildlife Destinations'), ('Off-the-beaten-path Destinations', 'Off-the-beaten-path Destinations')], max_length=100)),
                ('accommodation_preferences', models.CharField(blank=True, choices=[('Hotels', 'Hotels'), ('Resorts', 'Resorts'), ('Hostels', 'Hostels'), ('Vacation Rentals', 'Vacation Rentals'), ('Camping', 'Camping'), ('Boutique Hotels', 'Boutique Hotels')], max_length=100)),
                ('transportation_preferences', models.CharField(blank=True, choices=[('Group Tours with Transportation Included', 'Group Tours with Transportation Included'), ('Self-Guided Tours with Rental Car', 'Self-Guided Tours with Rental Car'), ('Public Transportation', 'Public Transportation'), ('Private Transportation (e.g., Chauffeur, Private Transfers)', 'Private Transportation (e.g., Chauffeur, Private Transfers)')], max_length=100)),
                ('meal_preferences', models.CharField(blank=True, choices=[('Local Cuisine', 'Local Cuisine'), ('Fine Dining', 'Fine Dining'), ('Street Food', 'Street Food'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-Free', 'Gluten-Free')], max_length=100)),
                ('language_preferences', models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Mandarin', 'Mandarin'), ('Italian', 'Italian'), ('Hindi', 'Hindi')], max_length=100)),
                ('budget_range', models.CharField(blank=True, choices=[('Budget', 'Budget'), ('Moderate', 'Moderate'), ('Luxury', 'Luxury')], max_length=100)),
                ('special_interests', models.CharField(blank=True, choices=[('History', 'History'), ('Art', 'Art'), ('Photography', 'Photography'), ('Adventure Sports', 'Adventure Sports'), ('Wildlife/Nature', 'Wildlife/Nature'), ('Wine Tasting', 'Wine Tasting')], max_length=100)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='mainapp.userprofile')),
=======
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('interested_places', models.ManyToManyField(to='mainapp.place')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
>>>>>>> origin/master
            ],
        ),
    ]
