# Generated by Django 4.2.11 on 2024-10-23 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("display_content", models.TextField()),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 star"),
                            (3, "3 star"),
                            (4, "4 star"),
                            (5, "5 star"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("priority", models.IntegerField(default=1)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interested_places",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="cost_per_person",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
        migrations.AddField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_future",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_past",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="max_capacity",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="trip",
            name="meeting_point",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participating_trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="trip",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="trip_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to="mainapp.trip",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="userchat",
            name="first_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userchat_first_person",
                to="mainapp.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userchat",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.chatgroup",
            ),
        ),
        migrations.AddField(
            model_name="userchat",
            name="second_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userchat_second_person",
                to="mainapp.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.place"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.place"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="mainapp.trip",
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatgroup",
            name="members",
            field=models.ManyToManyField(to="mainapp.userprofile"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.place"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="userchat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatmessage_userchat",
                to="mainapp.userchat",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user_id", "trip_id")},
        ),
        migrations.AlterUniqueTogether(
            name="userchat",
            unique_together={("first_person", "second_person", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "place")},
        ),
    ]
