# Generated by Django 4.2.11 on 2024-03-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accommodation_preferences',
            field=models.CharField(blank=True, choices=[('Hotels', 'Hotels'), ('Resorts', 'Resorts'), ('Hostels', 'Hostels'), ('Vacation Rentals', 'Vacation Rentals'), ('Camping', 'Camping'), ('Boutique Hotels', 'Boutique Hotels')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='activity_preferences',
            field=models.CharField(blank=True, choices=[('Outdoor Activities', 'Outdoor Activities'), ('Sightseeing/Cultural Activities', 'Sightseeing/Cultural Activities'), ('Food and Wine Experiences', 'Food and Wine Experiences'), ('Relaxation/Wellness Activities', 'Relaxation/Wellness Activities'), ('Adventure Sports', 'Adventure Sports'), ('Shopping', 'Shopping')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('Budget', 'Budget'), ('Moderate', 'Moderate'), ('Luxury', 'Luxury')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='destination_preferences',
            field=models.CharField(blank=True, choices=[('Beach Destinations', 'Beach Destinations'), ('Mountain Destinations', 'Mountain Destinations'), ('Urban Destinations', 'Urban Destinations'), ('Historical/Cultural Destinations', 'Historical/Cultural Destinations'), ('Nature/Wildlife Destinations', 'Nature/Wildlife Destinations'), ('Off-the-beaten-path Destinations', 'Off-the-beaten-path Destinations')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language_preferences',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Mandarin', 'Mandarin'), ('Italian', 'Italian'), ('Hindi', 'Hindi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='meal_preferences',
            field=models.CharField(blank=True, choices=[('Local Cuisine', 'Local Cuisine'), ('Fine Dining', 'Fine Dining'), ('Street Food', 'Street Food'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-Free', 'Gluten-Free')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='special_interests',
            field=models.CharField(blank=True, choices=[('History', 'History'), ('Art', 'Art'), ('Photography', 'Photography'), ('Adventure Sports', 'Adventure Sports'), ('Wildlife/Nature', 'Wildlife/Nature'), ('Wine Tasting', 'Wine Tasting')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='transportation_preferences',
            field=models.CharField(blank=True, choices=[('Group Tours with Transportation Included', 'Group Tours with Transportation Included'), ('Self-Guided Tours with Rental Car', 'Self-Guided Tours with Rental Car'), ('Public Transportation', 'Public Transportation'), ('Private Transportation (e.g., Chauffeur, Private Transfers)', 'Private Transportation (e.g., Chauffeur, Private Transfers)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='travel_style',
            field=models.CharField(choices=[('Adventure Seeker', 'Adventure Seeker'), ('Cultural Explorer', 'Cultural Explorer'), ('Luxury Traveler', 'Luxury Traveler'), ('Budget Traveler', 'Budget Traveler'), ('Family Traveler', 'Family Traveler'), ('Solo Traveler', 'Solo Traveler'), ('Eco-conscious Traveler', 'Eco-conscious Traveler')], max_length=100, null=True),
        ),
    ]
