# Generated by Django 5.0.2 on 2024-03-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_chatgroups_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat_group",
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="mainapp.userprofile",
            ),
        ),
    ]
