# Generated by Django 4.2.11 on 2024-03-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_userpreferences_user_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userpreferences'),
        ),
    ]
